{
 "title": "Devices",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Devices",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Desktops",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.device.type:Desktop",
     "timeField": "@timestamp"
    },
    {
     "alias": "Phones",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.device.type:Phone",
     "timeField": "@timestamp"
    },
    {
     "alias": "Tablets",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.device.type:Tablets",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Chrome",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.browser.name:Chrome",
     "timeField": "@timestamp"
    },
    {
     "alias": "Edge",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.browser.name:Edge",
     "timeField": "@timestamp"
    },
    {
     "alias": "Firefox",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.browser.name:Firefox",
     "timeField": "@timestamp"
    },
    {
     "alias": "SamsungBrowser",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.browser.name:SamsungBrowser",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Versions",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "v3.38.1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled* AND session.player.version:3.38.1",
     "timeField": "@timestamp"
    },
    {
     "alias": "v.3.37.0",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND event_name:ERROR AND data.log:*stalled*  AND session.player.version:3.37.0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Versions",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.version",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.media.type:audio AND data.log:*stalled*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "One Session",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "Desktops",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Logs",
     "metrics": [
      { "id": "1", "settings": { "size": "2000" }, "type": "logs" }
     ],
     "query": "session.media.type:audio AND session.device.id:852e5faf-2eb2-42b5-ab2b-eb716cece115",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}