{
 "title": "No User Agent",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Player Name (START events)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pillarbox Versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.version",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.player.name:Pillarbox",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Letterbox Versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.version",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.player.name:Letterbox",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Platform (START events)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.platform",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Players without User Agents (START event)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Samsung",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND (session.device.model:*samsung* OR session.device.model:*Samsung*)",
     "timeField": "@timestamp"
    },
    {
     "alias": "iPhone / iPad",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND (session.device.model:*iPhone* OR session.device.model:*iPad*)",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "session.device.model",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND NOT (session.device.model:*iPhone* OR session.device.model:*samsung* OR session.device.model:*Google* OR session.device.model:*iPad* OR session.device.model:*Fairphone* OR session.device.model:*Xiaomi* OR session.device.model:*HUAWEI*)",
     "timeField": "@timestamp"
    },
    {
     "alias": "Google",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.device.model:*Google*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fairphone",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.device.model:*Fairphone*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Xiaomi",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.device.model:*Xiaomi*",
     "timeField": "@timestamp"
    },
    {
     "alias": "HUAWEI",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (!_exists_:session.browser.user_agent)\nAND session.device.model:*HUAWEI*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}