{
 "title": "Block reason breakdown by media",
 "description": "This dashboard provides a comprehensive analysis of block reasons filtered by Media ID. ",
 "tags": [ "hidden" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player.platform\",\n  \"query\": \"event_name:START\",\n  \"size\": 10\n}"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "media_id", "label": "Media ID", "query": "urn:swisstxt:video:srf:1811521" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.media.id:${media_id}\nAND data.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Blocked",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.media.id:${media_id}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Block rate over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$block / $playing", "type": "math" }
   ]
  },
  {
   "title": "Block Reason Breakdown",
   "type": "piechart",
   "description": "The breakdown of blocking reasons for the selected period.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.media.id:${media_id}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Block reason over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.media.id:${media_id}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.origin",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.player.platform:${platform}\nAND session.media.id:\"${media_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latest Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR \nAND data.business_error:true\nAND session.media.id:\"${media_id}\"\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}