{
 "title": "Block Reason Report",
 "tags": [
  "pillarbox",
  "block_reason_report"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi, rio" },
   {
    "name": "type",
    "label": "Type",
    "query": "Audio : *\\:$bu\\:audio\\:*, Video : *\\:$bu\\:video\\:*"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.media.id:${type:raw}\nAND data.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Blocked",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.media.id:${type:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Block rate over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$block / $playing", "type": "math" }
   ]
  },
  {
   "title": "Most blocked media",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.media.id:${type:raw}\nAND data.business_error:true",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.media.id",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:Web\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most geoblocked IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_ip",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${type:raw}\nAND data.business_error:true\nAND data.error_type:GEOBLOCK",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "user_ip",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Block Reason Breakdown",
   "type": "piechart",
   "description": "The breakdown of blocking reasons for the selected period.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND session.media.id:${type:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}