{
 "title": "Daily Report",
 "tags": [
  "pillarbox",
  "daily_report"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi, rio" },
   {
    "name": "type",
    "label": "Type",
    "query": "Audio : *\\:$bu\\:audio\\:*, Video : *\\:$bu\\:video\\:*"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "The Success Rate is the ratio of START and STOP events to ERROR events, it measures the player reliability by comparing successful completions to failures.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:${type:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "1 - ($error / $playing)", "type": "math" },
    {
     "alias": "Sessions",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most conflicting media",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${type:raw}\nAND data.business_error:false",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.media.id",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most conflicting browsers",
   "type": "table",
   "description": "Web player only.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.browser.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Web\nAND session.media.id:${type:raw}\nAND data.business_error:false",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.browser.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:Web\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most conflicting device",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.device.model",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "session.player.platform",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      {
       "field": "session.device.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${type:raw}\nAND data.business_error:false",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.device.model",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.player.platform",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.device.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.media.id:${type:raw}\nAND data.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:${type:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}