{
 "title": "Device Fragmentation",
 "tags": [ "pillarbox" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Platform", "query": "Apple, Android" },
   {
    "name": "device",
    "label": "Device",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device.type\",\n  \"query\": \"event_name:START AND data.player.platform:$platform\",\n  \"size\": 10,\n  \"orderBy\": \"doc_count\"\n}\n"
   },
   {
    "name": "model",
    "label": "Model",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device.model\",\n  \"query\": \"event_name:START AND data.player.platform:$platform AND data.device.type:$device\",\n  \"size\": 10,\n  \"orderBy\": \"doc_count\"\n}\n"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "The average error rate for the selected browser and time range.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$error/$playing", "type": "math" }
   ]
  },
  {
   "title": "Adoption",
   "type": "stat",
   "description": "The percentage of sessions using the selected device. This percentage is relative to the selected platform total number of sessions.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$playing / $total", "type": "math" }
   ]
  },
  {
   "title": "Model trend",
   "type": "timeseries",
   "description": "Adoption rates of different device models for the selected tyoe across the selected time range.",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.device.model",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.device.type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS breakdown",
   "type": "barchart",
   "description": "The top 5 operating systems and their top 3 versions for the selected device type, model and time range.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.os.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "field": "data.os.version",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "3" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.device.type:${device}\nAND data.device.model:${model}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latest Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.player.platform:${platform}\nAND session.device.type:${device}\nAND session.device.model:${model}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}