{
 "title": "Error Breakdown",
 "tags": [ "pillarbox" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player.platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "bu",
    "label": "Business Unit",
    "query": "srf : urn\\:srf\\:*, rts : urn\\:rts\\:*, rsi : urn\\:rsi\\:*, rtr : urn\\:rtr\\:*, swi : urn\\:swi\\:*"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Errors",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "logs" }
       ],
       "query": "event_name:ERROR \nAND session.media.id:${bu:raw} \nAND session.player.platform:${platform}",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:ERROR \nAND session.media.id:${bu:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stop",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:STOP\nAND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Playing",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "NOT (event_name:ERROR OR STOP)\nAND session.media.id:${bu:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Model",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.device.model.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${bu:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.media.id:${bu:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR \nAND session.player.platform:${platform}\nAND session.media.id:${bu:raw}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}