{
 "title": "Event Breakdown",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player.platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "bu",
    "label": "Business Unit",
    "query": "srf : urn\\:srf\\:*, rts : urn\\:rts\\:*, rsi : urn\\:rsi\\:*, rtr : urn\\:rtr\\:*, swi : urn\\:swi\\:*"
   }
  ]
 },
 "panels": [
  {
   "title": "Event types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT event_name:HEARTBEAT\nAND (\n  (data.player.platform:${platform} AND data.media.id:${bu:raw})\n  OR \n  (session.player.platform:${platform} AND session.media.id:${bu:raw})\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(session.player.platform:${platform}\nAND session.media.id:${bu:raw} ) OR \n(data.player.platform:${platform}\nAND data.media.id:${bu:raw} )",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Platform Breakdown",
   "type": "piechart",
   "description": "Usage by platform for the selected time range.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player.platform.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND\ndata.player.platform:${platform} AND\ndata.media.id:${bu:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Platform Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player.platform.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND\n(data.player.platform:${platform}\nAND data.media.id:${bu:raw} )",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}