{
 "title": "Event Breakdown",
 "tags": [ "pillarbox" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi, rio" },
   {
    "name": "type",
    "label": "Type",
    "query": "Audio : *\\:$bu\\:audio\\:*, Video : *\\:$bu\\:video\\:*"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Event types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT event_name:HEARTBEAT\nAND (\n  (data.player.platform:${platform} AND data.media.id:${type:raw})\n  OR \n  (session.player.platform:${platform} AND session.media.id:${type:raw})\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(session.player.platform:${platform}\nAND session.media.id:${type:raw} ) OR \n(data.player.platform:${platform}\nAND data.media.id:${type:raw} )",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Platform Breakdown",
   "type": "piechart",
   "description": "Usage by platform for the selected time range.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player.platform",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player.platform:${platform}\nAND data.media.id:${type:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Platform Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player.platform",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (data.player.platform:${platform}\nAND data.media.id:${type:raw} )",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}