{
 "title": "IP Breakdown",
 "tags": [ "hidden" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "user_ip", "label": "IP" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Restriction Timeline",
   "type": "state-timeline",
   "description": "This timeline illustrates the specific time intervals during which access to media by the current IP address was restricted based on its geographical location.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Activity",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "user_ip:\"${user_ip}\"\nAND (\n  event_name:HEARTBEAT\n  OR (\n    event_name:ERROR AND data.error_type:GEOBLOCK \n  )\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:START\nAND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPN Status",
   "type": "state-timeline",
   "description": "Wether the IP has been detected as a VPN by the player.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$intervañ", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "user_ip:\"${user_ip}\" \nAND event_name:ERROR\nAND (data.vpn:true OR data.vpn:false)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR AND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}