{
 "title": "Live Breakdown",
 "tags": [ "pillarbox" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "video_live", "query": { "query": "" } },
   { "name": "scheduled", "query": { "query": "" } },
   { "name": "audio_live", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Video Livestreams",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "title", "text": "", "type": "string" },
      { "selector": "urn", "text": "", "type": "string" }
     ],
     "source": "url",
     "type": "json",
     "url": "/integrationlayer/2.0/${bu}/mediaList/video/livestreams",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "alias": "sessions",
     "bucketAggs": [
      {
       "field": "data.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:START \nAND data.player.platform:${platform}\nAND data.media.id:${video_live}",
     "timeField": "@timestamp"
    },
    {
     "alias": "errors",
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${video_live}\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Audio Livestreams",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "title", "text": "", "type": "string" },
      { "selector": "urn", "text": "", "type": "string" }
     ],
     "source": "url",
     "type": "json",
     "url": "/integrationlayer/2.0/${bu}/mediaList/audio/livestreams",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "alias": "sessions",
     "bucketAggs": [
      {
       "field": "data.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:START \nAND data.player.platform:${platform}\nAND data.media.id:${audio_live}",
     "timeField": "@timestamp"
    },
    {
     "alias": "errors",
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${audio_live}\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Scheduled Livestreams",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "columns": [
      { "selector": "title", "text": "", "type": "string" },
      { "selector": "urn", "text": "", "type": "string" },
      { "selector": "validFrom", "text": "", "type": "timestamp" }
     ],
     "source": "url",
     "type": "json",
     "url": "/integrationlayer/2.0/${bu}/mediaList/video/scheduledLivestreams/livecenter",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "alias": "sessions",
     "bucketAggs": [
      {
       "field": "data.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START \nAND data.player.platform:${platform}\nAND data.media.id:${scheduled}",
     "timeField": "@timestamp"
    },
    {
     "alias": "errors",
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${scheduled}\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}