{
 "title": "Metrics Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player.platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "bu",
    "label": "Business Unit",
    "query": "srf : urn\\:srf\\:*, rts : urn\\:rts\\:*, rsi : urn\\:rsi\\:*, rtr : urn\\:rtr\\:*, swi : urn\\:swi\\:*"
   },
   { "name": "media_id", "label": "Media Id", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND\nsession.player.platform:${platform} AND\nsession.media.id:${bu:raw} AND\nsession.media.id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND\nsession.player.platform:${platform} AND\nsession.media.id:urn\\:${bu}\\:* AND\nsession.media.id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Stall Rate",
   "type": "timeseries",
   "description": "Stall rate normalized to duration watched.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Stall Duration Rate",
   "type": "timeseries",
   "description": "Stall duration duration to watched ratio,",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Average Loading time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "Asset",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.qoe_timings.asset", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START AND \ndata.player.platform:${platform} AND\ndata.media.id:${bu:raw} AND\ndata.media.id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Metadata",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.qoe_timings.metadata", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START AND\ndata.player.platform:${platform} AND\ndata.media.id:urn\\:${bu}\\:* AND\ndata.media.id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Stall Duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.duration", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND\nsession.player.platform:${platform} AND\nsession.media.id:${bu:raw} AND\nsession.media.id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stall Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.count", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND\nsession.player.platform:${platform} AND\nsession.media.id:urn\\:${bu}\\:* AND\nsession.media.id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Buffer Duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.buffer_duration", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND\nsession.player.platform:${platform} AND\nsession.media.id:urn\\:${bu}\\:* AND\nsession.media.id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}