{
 "title": "Session Breakdown",
 "tags": [ "hidden" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "session_id", "label": "Session" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT event_name:START AND NOT event_name:ERROR AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT event_name:START AND NOT event_name:ERROR AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP) AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP) AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:ERROR AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}