{
 "title": "Analysis Player",
 "time": { "from": "2026-07-07T15:43:37.916Z", "to": "2026-07-07T18:50:55.754Z" },
 "templating": {
  "list": [
   { "name": "media_id", "label": "Media ID" }
  ]
 },
 "panels": [
  {
   "title": "data.name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:$media_id\nAND session.player.platform:*\nAND data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Letterbox User Agent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.browser.user_agent",
       "id": "3",
       "settings": { "min_doc_count": "5", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pillarbox User Agent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.browser.user_agent",
       "id": "3",
       "settings": { "min_doc_count": "5", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "data.name",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "5", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:$media_id\nAND session.player.platform:*\nAND data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PLAYBACK_MEDIA_SOURCE_ERROR",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ParserException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.log:*EXTM3U*",
     "timeField": "@timestamp"
    },
    {
     "alias": "CoreMediaErrorDomain",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.name:*CoreMediaErrorDomain*",
     "timeField": "@timestamp"
    },
    {
     "alias": "MEDIA_ERR_DECODE: 3",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.log:*MEDIA_ERR_DECODE*",
     "timeField": "@timestamp"
    },
    {
     "alias": "AVFoundationErrorDomain",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.name:*FoundationError*",
     "timeField": "@timestamp"
    },
    {
     "alias": "ExoTimeoutException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.name:ExoTimeoutException",
     "timeField": "@timestamp"
    },
    {
     "alias": "MediaCodecVideoDecoderException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.log:*CodecVideoDecoder*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Android PMSE",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.platform:Android",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web PMSE",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.platform:Web",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Apple PMSE",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.platform:Apple",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Letterbox Error Rate (10.1.0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:10.1.0\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:10.1.0\n",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Pillarbox Error Rate (16.0.1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:16.0.1\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:16.0.1\n",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Letterbox Error Rate (10.0.0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:10.0.0\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:10.0.0\n",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Pillarbox Error Rate (8.0.0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:8.0.0\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:8.0.0\n",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Letterbox Error Rate (3.38.1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:3.38.1",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Letterbox\nAND session.player.version:3.38.1",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Pillarbox Error Rate (1.36.2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "alias": "PMSE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:1.36.2\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:$media_id\nAND session.player.name:Pillarbox\nAND session.player.version:1.36.2\n",
     "timeField": "@timestamp"
    },
    { "expression": "1- $A/$B", "type": "math" }
   ]
  },
  {
   "title": "Duration",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Logs",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "logs" }
     ],
     "query": "data.error_type:PLAYBACK_MEDIA_SOURCE_ERROR\nAND session.media.id:$media_id\nAND data.name:ParserException",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}