{
 "title": "Browsers",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Unique Session Browsers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.browser.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND _exists_:session.browser.name\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "no Browser name",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Session Browsers (Errors)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.browser.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:ERROR\nAND _exists_:session.browser.name\n",
     "timeField": "@timestamp"
    },
    {
     "alias": "no Browser name",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:ERROR\nAND NOT _exists_:session.browser.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "No Browser Name Device Types",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.device.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "No Browser Name Platform",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.platform",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "With Browser Name Platform",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.player.platform",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND _exists_:session.browser.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "No Browser Name Device Model",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "alias": "iPhones",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND session.device.model:*iPhone*",
     "timeField": "@timestamp"
    },
    {
     "alias": "samsung",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND NOT session.device.model:*iPhone*\nAND session.device.model:*samsung*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fairphone",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND NOT session.device.model:*iPhone*\nAND NOT session.device.model:*samsung*\nAND session.device.model:*Fairphone*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Google",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND NOT session.device.model:*iPhone*\nAND NOT session.device.model:*samsung*\nAND NOT session.device.model:*Fairphone*\nAND session.device.model:*Google*",
     "timeField": "@timestamp"
    },
    {
     "alias": "iPad",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND NOT session.device.model:*iPhone*\nAND NOT session.device.model:*samsung*\nAND NOT session.device.model:*Fairphone*\nAND NOT session.device.model:*Google*\nAND session.device.model:*iPad*",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "session.device.model",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND NOT _exists_:session.browser.name\nAND NOT session.device.model:*iPhone*\nAND NOT session.device.model:*samsung*\nAND NOT session.device.model:*Fairphone*\nAND NOT session.device.model:*Google*\nAND NOT session.device.model:*iPad*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}