{
 "title": "Concurrent Viewers Insight",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mediatype", "label": "Media Type", "query": "audio,video" },
   { "name": "bu", "label": "BU", "query": "srf,rts,rsi,rtr,playsuisse" }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Viewers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:HEARTBEAT\nAND session.media.bu:$bu\nAND session.media.type:$mediatype",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "START events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.bu:$bu\nAND session.media.type:$mediatype",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "STOP events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "durations of events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Duration: 0",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND data.playback_duration:0",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: up to 1 minute",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[1 TO 60000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: 1 to 10 minutes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[60000 TO 600000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: 10 to 60 minutes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[600000 TO 3600000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: more than 1 hour",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[3600000 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "durations of events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Duration: 0",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND data.playback_duration:0",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: up to 1 minute",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[1 TO 60000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: 1 to 10 minutes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[60000 TO 600000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: 10 to 60 minutes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[600000 TO 3600000]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Duration: more than 1 hour",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "event_name:STOP\nAND session.media.bu:$bu\nAND session.media.type:$mediatype\nAND NOT data.playback_duration:0\nAND data.playback_duration:[3600000 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ERROR events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.media.bu:$bu\nAND session.media.type:$mediatype",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Concurrent Viewers by BU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.bu",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:HEARTBEAT",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}