{
 "title": "DRM Streams",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Stream",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "widevine",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.asset_url:*widevine*\nAND NOT session.media.asset_url:*playready*",
     "timeField": "@timestamp"
    },
    {
     "alias": "fairplay",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.asset_url:*fairplay*",
     "timeField": "@timestamp"
    },
    {
     "alias": "widevine-playready",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.asset_url:*playready*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origins SRF",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.short_origin",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND session.media.short_origin:*srf*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origins RTS",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.short_origin",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND session.media.short_origin:*rts*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origins RSI",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.short_origin",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND session.media.short_origin:*rsi*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origins RTR",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.short_origin",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:START\nAND session.media.short_origin:*rtr*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Capabilities",
   "type": "stat",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.capabilities.widevine.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "session.capabilities.playReady.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Type L1",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.device.type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "session.capabilities.widevine.level:L1\nAND _exists_:session.device.type",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Model L1",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.device.model",
       "id": "3",
       "settings": { "min_doc_count": "10", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "session.capabilities.widevine.level:L1\nAND _exists_:session.device.type",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}