{
 "title": "Errors (Business/Non-Business)",
 "time": { "from": "2026-09-13T12:45:00.000Z", "to": "2026-09-13T16:00:00.000Z" },
 "panels": [
  {
   "title": "all errors (non business)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "Business Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true",
     "timeField": "@timestamp"
    },
    {
     "alias": "Not Business Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Android Media ID 403 Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:false\nAND data.message:\"Response code: 403\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all errors (business)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND (data.message:STARTDATE OR data.message:GEOBLOCK OR data.message:VPNORPROXYDETECTED OR data.message:UNKNOWN)",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true\nAND NOT (data.message:STARTDATE OR data.message:GEOBLOCK OR data.message:VPNORPROXYDETECTED OR data.message:UNKNOWN)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all errors (business) block reason",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.block_reason",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all android errors (non business)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all android errors (business)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:true\nAND (data.message:STARTDATE OR data.message:GEOBLOCK OR data.message:VPNORPROXYDETECTED OR data.message:UNKNOWN)",
     "timeField": "@timestamp"
    },
    {
     "alias": "java.net.UnknownHostException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:true\nAND data.message:*java.net.UnknownHostException*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}