{
 "title": "Live Breakdown (edit)",
 "tags": [ "hidden" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr" },
   { "name": "type", "label": "Type", "query": "audio, video" },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "live_ids", "query": { "query": "" } },
   { "name": "live_ids_str", "query": { "query": "" } },
   {
    "name": "p95",
    "query": {}
   },
   {
    "name": "not_browser",
    "query": "\"\",SamsungBrowser"
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}\nAND NOT session.browser.name:${not_browser}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "The Success Rate measures player reliability as the ratio of START to ERROR events, excluding failures caused by blocked reasons,  unsupported DRM errors or connection errors.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.id:${live_ids}\nAND NOT session.browser.name:${not_browser}",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "1 - ($error / $playing)", "type": "math" },
    {
     "alias": "Sessions",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.id:${live_ids}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Livestreams",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "columns": [
      { "selector": "key", "text": "media_id", "type": "string" },
      {
       "selector": "p50_load_time.percentile.values.50\\.0",
       "text": "p50",
       "type": "number"
      },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      { "selector": "starts.doc_count", "text": "sessions", "type": "number" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "aggregations.by_media_id.buckets",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"wildcard\": { \"session.media.bu\": \"${bu}\" } },\n        { \"wildcard\": { \"session.media.type\": \"${type}\" } },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } },\n        { \"terms\": { \"session.media.id\": ${live_ids:json} }}\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_media_id\": {\n      \"terms\": {\n        \"field\": \"session.media.id\",\n        \"size\": 500,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "title", "text": "", "type": "string" },
      { "selector": "urn", "text": "media_id", "type": "string" },
      { "selector": "validFrom", "text": "", "type": "timestamp" },
      { "selector": "imageUrl", "text": "thumbnail", "type": "string" },
      { "selector": "urn", "text": "demo", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "mediaList",
     "source": "url",
     "type": "json",
     "url": "/integrationlayer/2.0/mediaList/byUrns?urns=${live_ids_str}",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Error Type Breakdown",
   "type": "piechart",
   "description": "Error Type Breakdown for the selected browser and time range.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}\nAND NOT session.browser.name:${not_browser}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors rate over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$error / $playing", "type": "math" }
   ]
  },
  {
   "title": "Error by platform",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(aggregations.by_platform.buckets, function($bucket) {\n  {\n    \"player_platform\": $bucket.key,\n    \"starts\": $bucket.starts.doc_count,\n    \"errors\": $bucket.errors.doc_count,\n    \"error_rate\": $bucket.error_rate.value,\n    \"p50_load_time\": $bucket.p50_load_time.percentile.values.\"50.0\"\n  }\n})",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"terms\": { \"session.media.id\": ${live_ids:json} }},\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_platform\": {\n      \"terms\": {\n        \"field\": \"session.player.platform\",\n        \"size\": 500,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Most Conflicting Player Versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(aggregations.by_player_combo.buckets, function($bucket) {\n  {\n    \"player_name\": $bucket.key[0],\n    \"player_version\": $bucket.key[1],\n    \"player_platform\": $bucket.key[2],\n    \"starts\": $bucket.starts.doc_count,\n    \"errors\": $bucket.errors.doc_count,\n    \"error_rate\": $bucket.error_rate.value,\n    \"p50_load_time\": $bucket.p50_load_time.percentile.values.\"50.0\"\n  }\n})",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"terms\": { \"session.media.id\": ${live_ids:json} } },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_player_combo\": {\n      \"multi_terms\": {\n        \"terms\": [\n          { \"field\": \"session.player.name\" },\n          { \"field\": \"session.player.version\" },\n          { \"field\": \"session.player.platform\" }\n        ],\n        \"size\": 3000,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${live_ids}\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Perceived delay",
   "type": "timeseries",
   "description": "The median quality of experience loading time, i.e., how long the user perceives the video to load.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session.qoe_timings.total", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" },
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay historgram",
   "type": "barchart",
   "description": "Distribution of sessions across perceived loading times, capped at the 95th percentile to exclude outliers.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "session.qoe_timings.total", "id": "2", "settings": { "interval": "10", "min_doc_count": "10" }, "type": "histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}\nAND session.qoe_timings.total:[* TO $p95]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Frame Drops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average stall duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.frame_drops", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "(event_name:HEARTBEAT OR event_name:STOP)\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Stall Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Average stall duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.duration", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "(event_name:HEARTBEAT OR event_name:STOP)\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Stall Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "alias": "Average stall count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.count", "id": "1", "type": "avg" }
     ],
     "query": "(event_name:HEARTBEAT OR event_name:STOP)\nAND session.media.id:${live_ids}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}