{
 "title": "New dashboard",
 "time": { "from": "2026-09-13T12:45:00.000Z", "to": "2026-09-13T16:00:00.000Z" },
 "panels": [
  {
   "title": "urn\\:swisstxt\\:video\\:rsi\\:1828080",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND session.media.id:urn\\:swisstxt\\:video\\:rsi\\:1828080\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "urn\\:srf\\:video\\:c49c1d73-2f70-0001-138a-15e0c4ccd3d0",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND session.media.id:urn\\:srf\\:video\\:c49c1d73-2f70-0001-138a-15e0c4ccd3d0\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Media ID 403 Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:false\nAND data.message:\"Response code: 403\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:true",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.business_error",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "all android errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:Android\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}