{
 "title": "ParserException",
 "time": { "from": "now-9d", "to": "now" },
 "templating": {
  "list": [
   { "name": "_min_starts", "label": "Session Minimum", "query": "0,1,10,100,500,1000,2000,5000" },
   { "name": "platform", "label": "Platform", "query": "All,Web,Mobile" },
   {
    "name": "ip",
    "label": "IP",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Applications Breakdown",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "application", "text": "application", "type": "string" },
      { "selector": "errors", "text": "errors", "type": "number" },
      { "selector": "starts", "text": "sessions", "type": "number" },
      { "selector": "p50_load_time", "text": "p50", "type": "number" },
      { "selector": "error_rate", "text": "error_rate", "type": "number" },
      { "selector": "platform_type", "text": "platform_type", "type": "string" },
      { "selector": "platform_detail", "text": "platform_detail", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "$filter(\n  $append(\n    $map(aggregations.web_apps.by_application.buckets, function($b) {\n      {\n        \"platform_type\": \"Web\",\n        \"platform_detail\": \"Browser\",  /* Could extract from data */\n        \"application\": $b.key,\n        \"starts\": $b.starts.doc_count,\n        \"errors\": $b.errors.doc_count,\n        \"error_rate\": $b.error_rate.value,\n        \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n      }\n    }),\n    $map(aggregations.mobile_apps.by_application.buckets, function($b) {\n      {\n        \"platform_type\": \"Mobile\",\n        \"platform_detail\": $b.platform.value,  /* e.g., \"iOS\", \"Android\" */\n        \"application\": $b.key,\n        \"starts\": $b.starts.doc_count,\n        \"errors\": $b.errors.doc_count,\n        \"error_rate\": $b.error_rate.value,\n        \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n      }\n    })\n  ),\n  function($row) {\n    $row.starts >= $number($_min_starts) \n    and\n   (\"${platform}\" = \"All\" \n   or \n   $row.platform_type = \"${platform}\")\n  }\n)",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\r\n  \"size\": 0,\r\n  \"query\": {\r\n    \"bool\": {\r\n      \"filter\": [\r\n        {\r\n          \"range\": {\r\n            \"@timestamp\": {\r\n              \"gte\": \"${__from}\",\r\n              \"lte\": \"${__to}\"\r\n            }\r\n          }\r\n        },\r\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\r\n      ]\r\n    }\r\n  },\r\n  \"aggs\": {\r\n    \"web_apps\": {\r\n      \"filter\": {\r\n        \"bool\": {\r\n          \"must_not\": [\r\n            { \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] } }\r\n          ]\r\n        }\r\n      },\r\n      \"aggs\": {\r\n        \"by_application\": {\r\n          \"terms\": {\r\n            \"field\": \"session.media.short_origin\",\r\n            \"size\": 500,\r\n            \"order\": { \"errors\": \"desc\" }\r\n          },\r\n          \"aggs\": {\r\n            \"errors\": {\r\n              \"filter\": {\r\n                \"bool\": {\r\n                  \"filter\": [\r\n                    { \"term\": { \"event_name\": \"ERROR\" } },\r\n                    { \"term\": { \"data.business_error\": false } }\r\n                  ],\r\n                  \"must_not\": [\r\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\", \"STARTDATE\", \"PLAYBACK_UNSUPPORTED_MEDIA\"] }},\r\n\t\t\t\t\t{ \"terms\": { \"data.name\": [\"MEDIA_ERR_CUSTOM: 0\", \"MEDIA_ERR_ABORTED: 1\"] } }\r\n                  ]\r\n                }\r\n              }\r\n            },\r\n            \"starts\": {\r\n              \"filter\": { \"term\": { \"event_name\": \"START\"} }\r\n            },\r\n            \"error_rate\": {\r\n              \"bucket_script\": {\r\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\r\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\r\n              }\r\n            },\r\n            \"p50_load_time\": {\r\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\r\n              \"aggs\": {\r\n                \"percentile\": {\r\n                  \"percentiles\": {\r\n                    \"field\": \"session.qoe_timings.total\",\r\n                    \"percents\": [50]\r\n                  }\r\n                }\r\n              }\r\n            }\r\n          }\r\n        }\r\n      }\r\n    },\r\n\r\n    \"mobile_apps\": {\r\n      \"filter\": {\r\n        \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] }\r\n      },\r\n      \"aggs\": {\r\n        \"by_application\": {\r\n          \"terms\": {\r\n            \"field\": \"session.application.id\",\r\n            \"size\": 500,\r\n            \"order\": { \"errors\": \"desc\" }\r\n          },\r\n          \"aggs\": {\r\n            \"errors\": {\r\n              \"filter\": {\r\n                \"bool\": {\r\n                  \"filter\": [\r\n                    { \"term\": { \"event_name\": \"ERROR\" } },\r\n                    { \"term\": { \"data.business_error\": false } }\r\n                  ],\r\n                  \"must_not\": [\r\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\r\n                  ]\r\n                }\r\n              }\r\n            },\r\n            \"starts\": {\r\n              \"filter\": { \"term\": { \"event_name\": \"START\"} }\r\n            },\r\n            \"error_rate\": {\r\n              \"bucket_script\": {\r\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\r\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\r\n              }\r\n            },\r\n            \"p50_load_time\": {\r\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\r\n              \"aggs\": {\r\n                \"percentile\": {\r\n                  \"percentiles\": {\r\n                    \"field\": \"session.qoe_timings.total\",\r\n                    \"percents\": [50]\r\n                  }\r\n                }\r\n              }\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "ch.srf.mobile.srfplayer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.srf.mobile.srfplayer\" OR session.application.id:\"ch.srf.mobile.srfplayer\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ch.rsi.player",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.rsi.player\" OR session.application.id:\"ch.rsi.player\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ch.rts.player",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.rts.player\" OR session.application.id:\"ch.rts.player\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ch.srf.sport",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.srf.sport\" OR session.application.id:\"ch.srf.sport\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ch.rsi.app",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.rsi.app\" OR session.application.id:\"ch.rsi.app\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ch.rts.rtsinfo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.message",
       "id": "3",
       "settings": { "min_doc_count": "10", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"ch.rts.rtsinfo\" OR session.application.id:\"ch.rts.rtsinfo\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(Web) www.srf.ch/play",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (session.media.short_origin:\"www.srf.ch/play\" OR session.application.id:\"www.srf.ch/play\")\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "targets": [
    {
     "alias": "ParserException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (data.name:ParserException OR data.name:*EXTM3U header*)\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.name",
       "id": "3",
       "settings": { "min_doc_count": "10", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND NOT (data.name:ParserException OR data.name:*EXTM3U header*)\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "alias": "ParserException",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Logs",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "logs" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND data.name:ParserException\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ParserException",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.asset_url",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (data.name:ParserException OR data.name:*EXTM3U header*)\nAND NOT data.error_type:PLAYBACK_UNSUPPORTED_MEDIA\nAND NOT data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}