{
 "title": "Players",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Letterbox and  Pillarbox unique sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Pillarbox Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "session.player.name:Pillarbox\nAND session.media.type:audio\nAND (data.url:*audiostreaming* OR session.media.origin:*live*)",
     "timeField": "@timestamp"
    },
    {
     "alias": "Letterbox Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "session.player.name:Letterbox\nAND session.media.type:audio\nAND (data.url:*audiostreaming* OR session.media.origin:*live*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Letterbox / Pillarbox",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Pillarbox",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.player.name:Pillarbox\nAND data.business_error:false\nAND (data.url:*audiostreaming* OR session.media.origin:*live*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Letterbox",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session.player.name:Letterbox\nAND data.business_error:false\nAND (data.url:*audiostreaming* OR session.media.origin:*live*)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}