{
 "title": "Daily Report",
 "tags": [
  "pillarbox",
  "daily_report"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   {
    "name": "bu",
    "label": "Business Unit",
    "query": "srf, rts, rsi, rtr, swi, playsuisse"
   },
   { "name": "type", "label": "Type", "query": "audio, video" },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "swisstxt",
    "query": "Include SwissTXT : (true OR false), Only SwissTXT : true, Exclude SwissTXT : false"
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "The Success Rate measures player reliability as the ratio of START to ERROR events, excluding failures caused by blocked reasons,  unsupported DRM errors or connection errors.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.player.platform:${platform}\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "1 - ($error / $playing)", "type": "math" },
    {
     "alias": "Sessions",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most conflicting media",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 9 },
   "targets": [
    {
     "columns": [
      { "selector": "key", "text": "media_id", "type": "string" },
      {
       "selector": "p50_load_time.percentile.values.50\\.0",
       "text": "p50",
       "type": "number"
      },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      { "selector": "starts.doc_count", "text": "sessions", "type": "number" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" },
      { "selector": "key", "text": "demo", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "aggregations.by_media_id.buckets",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"wildcard\": { \"session.media.bu\": \"${bu}\" } },\n        { \"wildcard\": { \"session.media.type\": \"${type}\" } },\n        {\n          \"query_string\": {\n            \"query\": \"session.media.swisstxt:${swisstxt:raw}\"\n          }\n        },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_media_id\": {\n      \"terms\": {\n        \"field\": \"session.media.id\",\n        \"size\": 500,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most conflicting devices",
   "type": "table",
   "description": "Apple and Android Players Only",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "key", "text": "device_model", "type": "string" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" },
      { "selector": "starts.doc_count", "text": "sessions", "type": "number" },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      {
       "selector": "p50_load_time.percentile.values.50\\.0",
       "text": "p50",
       "type": "number"
      }
     ],
     "parser": "backend",
     "root_selector": "aggregations.by_device_model.buckets",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"wildcard\": { \"session.media.bu\": \"${bu}\" } },\n        { \"wildcard\": { \"session.media.type\": \"${type}\" } },\n        {\n          \"query_string\": {\n            \"query\": \"session.media.swisstxt:${swisstxt:raw}\"\n          }\n        },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ],\n      \"must_not\": [\n        { \"term\":  { \"session.player.platform\": \"Web\" } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_device_model\": {\n      \"terms\": {\n        \"field\": \"session.device.model\",\n        \"size\": 500,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Most conflicting browsers",
   "type": "table",
   "description": "Web player only.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "key", "text": "browser_name", "type": "string" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" },
      { "selector": "starts.doc_count", "text": "starts", "type": "number" },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      {
       "selector": "p50_load_time.percentile.values.50\\.0",
       "text": "p50",
       "type": "number"
      }
     ],
     "parser": "backend",
     "root_selector": "aggregations.by_browser_name.buckets",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"wildcard\": { \"session.media.bu\": \"${bu}\" } },\n        { \"wildcard\": { \"session.media.type\": \"${type}\" } },\n        {\n          \"query_string\": {\n            \"query\": \"session.media.swisstxt:${swisstxt:raw}\"\n          }\n        },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ],\n      \"must_not\": [\n        { \"terms\":  { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_browser_name\": {\n      \"terms\": {\n        \"field\": \"session.browser.name\",\n        \"size\": 500,\n        \"order\": { \"errors\": \"desc\" }\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Most conflicting Applications",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "application", "text": "application", "type": "string" },
      { "selector": "errors", "text": "errors", "type": "number" },
      { "selector": "starts", "text": "sessions", "type": "number" },
      { "selector": "p50_load_time", "text": "p50", "type": "number" },
      { "selector": "error_rate", "text": "error_rate", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "$append(\n  $map(aggregations.web_apps.by_application.buckets, function($b) {\n    {\n      \"application\": $b.key,\n      \"starts\": $b.starts.doc_count,\n      \"errors\": $b.errors.doc_count,\n      \"error_rate\": $b.error_rate.value,\n      \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n    }\n  }),\n  $map(aggregations.mobile_apps.by_application.buckets, function($b) {\n    {\n      \"application\": $b.key,\n      \"starts\": $b.starts.doc_count,\n      \"errors\": $b.errors.doc_count,\n      \"error_rate\": $b.error_rate.value,\n      \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n    }\n  })\n)",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"wildcard\": { \"session.media.bu\": \"${bu}\" } },\n        { \"wildcard\": { \"session.media.type\": \"${type}\" } },\n        {\n          \"query_string\": {\n            \"query\": \"session.media.swisstxt:${swisstxt:raw}\"\n          }\n        },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"web_apps\": {\n      \"filter\": {\n        \"bool\": {\n          \"must_not\": [\n            { \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] } }\n          ]\n        }\n      },\n      \"aggs\": {\n        \"by_application\": {\n          \"terms\": {\n            \"field\": \"session.media.short_origin\",\n            \"size\": 500,\n            \"order\": { \"errors\": \"desc\" }\n          },\n          \"aggs\": {\n            \"errors\": {\n              \"filter\": {\n                \"bool\": {\n                  \"filter\": [\n                    { \"term\": { \"event_name\": \"ERROR\" } },\n                    { \"term\": { \"data.business_error\": false } }\n                  ],\n                  \"must_not\": [\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n                  ]\n                }\n              }\n            },\n            \"starts\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } }\n            },\n            \"error_rate\": {\n              \"bucket_script\": {\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n              }\n            },\n            \"p50_load_time\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\n              \"aggs\": {\n                \"percentile\": {\n                  \"percentiles\": {\n                    \"field\": \"session.qoe_timings.total\",\n                    \"percents\": [50]\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    },\n\n    \"mobile_apps\": {\n      \"filter\": {\n        \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] }\n      },\n      \"aggs\": {\n        \"by_application\": {\n          \"terms\": {\n            \"field\": \"session.application.id\",\n            \"size\": 500,\n            \"order\": { \"errors\": \"desc\" }\n          },\n          \"aggs\": {\n            \"errors\": {\n              \"filter\": {\n                \"bool\": {\n                  \"filter\": [\n                    { \"term\": { \"event_name\": \"ERROR\" } },\n                    { \"term\": { \"data.business_error\": false } }\n                  ],\n                  \"must_not\": [\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n                  ]\n                }\n              }\n            },\n            \"starts\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } }\n            },\n            \"error_rate\": {\n              \"bucket_script\": {\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n              }\n            },\n            \"p50_load_time\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\n              \"aggs\": {\n                \"percentile\": {\n                  \"percentiles\": {\n                    \"field\": \"session.qoe_timings.total\",\n                    \"percents\": [50]\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Error Type Breakdown",
   "type": "piechart",
   "description": "Error Type Breakdown for the selected browser and time range.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.bu:${bu}\nAND session.media.type:${type}\nAND session.media.swisstxt:${swisstxt:raw}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$error / $playing", "type": "math" }
   ]
  }
 ]
}