{
 "title": "IP Breakdown",
 "tags": [ "hidden" ],
 "time": { "from": "2025-06-24T08:53:42.255Z", "to": "2025-07-24T08:53:42.255Z" },
 "templating": {
  "list": [
   { "name": "user_ip", "label": "IP", "query": "117.200.116.92" },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Blocked",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND user_ip:${user_ip}\nAND data.business_error:true\nAND data.block_reason:(GEOBLOCK OR VPNORPROXYDETECTED)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "The Success Rate measures player reliability as the ratio of START to ERROR events, excluding failures caused by blocked reasons,  unsupported DRM errors or connection errors.",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START \nAND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Restriction Timeline",
   "type": "timeseries",
   "description": "This timeline illustrates the specific time intervals during which access to media by the current IP address was restricted based on its geographical location.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Starts",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_ip:\"${user_ip}\" AND event_name:START",
     "timeField": "@timestamp"
    },
    {
     "alias": "Geoblock",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_ip:\"${user_ip}\"\nAND event_name:ERROR\nAND data.block_reason:GEOBLOCK",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_ip:\"${user_ip}\" \nAND event_name:ERROR \nAND data.business_error:false",
     "timeField": "@timestamp"
    },
    {
     "alias": "VPN Detected",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_ip:\"${user_ip}\"\nAND event_name:ERROR\nAND data.block_reason:VPNORPROXYDETECTED",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latest Sessions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:START\nAND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "session_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.business_error",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP)\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay",
   "type": "timeseries",
   "description": "The median quality of experience loading time, i.e., how long the user perceives the video to load.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session.qoe_timings.total", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" },
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR AND user_ip:\"${user_ip}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Frame Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average stall duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.frame_drops", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP)\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Stall Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Average stall duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.duration", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP)\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median Stall Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "alias": "Average stall count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall.count", "id": "1", "type": "avg" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP)\nAND user_ip:${user_ip}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}