{
 "title": "Live Overview",
 "tags": [ "pillarbox" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   { "name": "type", "query": "audio, video" },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "live_ids_srf", "query": { "query": "" } },
   { "name": "live_ids_rts", "query": { "query": "" } },
   { "name": "live_ids_rsi", "query": { "query": "" } },
   { "name": "live_ids_rtr", "query": { "query": "" } },
   { "name": "p95", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "bu", "text": "bu", "type": "string" },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" },
      { "selector": "starts.doc_count", "text": "sessions", "type": "number" },
      { "selector": "starts.p50.values.50\\.0", "text": "load_time", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "$each(aggregations.by_bu.buckets, function($v, $k) {\n  $merge([{ \"bu\": $k }, $v])\n})",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_bu\": {\n      \"filters\": {\n        \"filters\": {\n          \"srf\": { \"terms\": { \"session.media.id\": ${live_ids_srf:json} } },\n          \"rts\": { \"terms\": { \"session.media.id\": ${live_ids_rts:json} } },\n          \"rsi\": { \"terms\": { \"session.media.id\": ${live_ids_rsi:json} } },\n          \"rtr\": { \"terms\": { \"session.media.id\": ${live_ids_rtr:json} } }\n        }\n      },\n      \"aggs\": {\n        \"starts\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"p50\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        },\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"term\": { \"data.error_type\": \"DRM_NOT_SUPPORTED\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"errors\": \"errors._count\",\n              \"starts\": \"starts._count\"\n            },\n            \"script\": \"params.starts > 0 ? params.errors / params.starts : 0\"\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Type Breakdown",
   "type": "piechart",
   "description": "Error Type Breakdown for the selected browser and time range.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "The Success Rate measures player reliability as the ratio of START to ERROR events, excluding failures caused by blocked reasons or unsupported DRM errors.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "1 - ($error / $playing)", "type": "math" },
    {
     "alias": "Sessions",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay",
   "type": "timeseries",
   "description": "The median quality of experience loading time, i.e., how long the user perceives the video to load.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session.qoe_timings.total", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" },
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay historgram",
   "type": "barchart",
   "description": "Distribution of sessions across perceived loading times, capped at the 95th percentile to exclude outliers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "session.qoe_timings.total", "id": "2", "settings": { "interval": "10", "min_doc_count": "10" }, "type": "histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND (\n  session.media.id:${live_ids_srf} OR\n  session.media.id:${live_ids_rts} OR\n  session.media.id:${live_ids_rsi} OR\n  session.media.id:${live_ids_rtr}\n)\nAND session.qoe_timings.total:[* TO $p95]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}