{
 "title": "Session Breakdown",
 "tags": [ "hidden" ],
 "time": { "from": "2026-09-17T08:55:08.014Z", "to": "2026-09-24T08:55:08.014Z" },
 "templating": {
  "list": [
   {
    "name": "session_id",
    "label": "Session",
    "query": "8cb3c70f-dac4-4f34-aa3b-2778df9e4ffc"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT event_name:START AND NOT event_name:ERROR AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT event_name:START AND NOT event_name:ERROR AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP) AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "event_name:(HEARTBEAT OR STOP) AND session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "session_id:\"${session_id}\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}