{
 "title": "Show Breakdown",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform", "label": "Player Platform", "query": "Android, Apple, Web" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "show", "label": "Show" },
   {
    "name": "urns",
    "query": {}
   },
   {
    "name": "urns_str",
    "query": {}
   },
   {
    "name": "p95",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "imageUrl", "text": "Thumbnail", "type": "string" },
      { "selector": "title", "text": "Title", "type": "string" },
      { "selector": "numberOfEpisodes", "text": "# Episodes", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "show",
     "source": "url",
     "type": "json",
     "url": "https://il.srgssr.ch/integrationlayer/2.0/episodeComposition/latestByShow/byUrn/${show}?vector=srgplay&pageSize=1",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total number of sessions",
   "type": "stat",
   "description": "The total number of sessions for the selected period.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Sessions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${urns}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.media.id:${urns}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "The Success Rate measures player reliability as the ratio of START to ERROR events, excluding failures caused by blocked reasons,  unsupported DRM errors or connection errors.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "playing",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.id:${urns}",
     "timeField": "@timestamp"
    },
    {
     "alias": "error",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND NOT data.error_type:(DRM_NOT_SUPPORTED OR CONNECTION_ERROR)\nAND data.business_error:false\nAND session.player.platform:${platform}\nAND session.media.id:${urns}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "1 - ($error / $playing)", "type": "math" },
    {
     "alias": "Sessions",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.player.platform:${platform}\nAND session.media.id:${urns}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "columns": [
      { "selector": "key", "text": "media_id", "type": "string" },
      {
       "selector": "p50_load_time.percentile.values.50\\.0",
       "text": "p50",
       "type": "number"
      },
      { "selector": "error_rate.value", "text": "error_rate", "type": "number" },
      { "selector": "starts.doc_count", "text": "sessions", "type": "number" },
      { "selector": "errors.doc_count", "text": "errors", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "aggregations.by_media_id.buckets",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } },\n        { \"terms\": { \"session.media.id\": ${urns:json} }}\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_media_id\": {\n      \"terms\": {\n        \"field\": \"session.media.id\",\n        \"size\": 500\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "title", "text": "", "type": "string" },
      { "selector": "urn", "text": "media_id", "type": "string" },
      { "selector": "validFrom", "text": "", "type": "timestamp" },
      { "selector": "imageUrl", "text": "thumbnail", "type": "string" },
      { "selector": "urn", "text": "demo", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "mediaList",
     "source": "url",
     "type": "json",
     "url": "/integrationlayer/2.0/mediaList/byUrns?urns=${urns_str}",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Error Type Breakdown",
   "type": "piechart",
   "description": "Error Type Breakdown for the selected browser and time range.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.error_type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.business_error:false\nAND session.media.id:${urns}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors rate over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$error / $playing", "type": "math" }
   ]
  },
  {
   "title": "Error by platform",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(aggregations.by_platform.buckets, function($bucket) {\n  {\n    \"player_platform\": $bucket.key,\n    \"starts\": $bucket.starts.doc_count,\n    \"errors\": $bucket.errors.doc_count,\n    \"error_rate\": $bucket.error_rate.value,\n    \"p50_load_time\": $bucket.p50_load_time.percentile.values.\"50.0\"\n  }\n})",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"terms\": { \"session.media.id\": ${urns:json} }},\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"by_platform\": {\n      \"terms\": {\n        \"field\": \"session.player.platform\",\n        \"size\": 500\n      },\n      \"aggs\": {\n        \"errors\": {\n          \"filter\": {\n            \"bool\": {\n              \"filter\": [\n                { \"term\": { \"event_name\": \"ERROR\" } },\n                { \"term\": { \"data.business_error\": false } }\n              ],\n              \"must_not\": [\n                { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n              ]\n            }\n          }\n        },\n        \"starts\": {\n          \"filter\": {\n            \"bool\": {\n              \"must\": [\n                { \"term\": { \"event_name\": \"START\" } }\n              ]\n            }\n          }\n        },\n        \"error_rate\": {\n          \"bucket_script\": {\n            \"buckets_path\": {\n              \"err\": \"errors>_count\",\n              \"sess\": \"starts>_count\"\n            },\n            \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n          }\n        },\n        \"p50_load_time\": {\n          \"filter\": {\n            \"term\": { \"event_name\": \"START\" }\n          },\n          \"aggs\": {\n            \"percentile\": {\n              \"percentiles\": {\n                \"field\": \"session.qoe_timings.total\",\n                \"percents\": [50]\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Most conflicting Applications",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 34 },
   "targets": [
    {
     "columns": [
      { "selector": "application", "text": "application", "type": "string" },
      { "selector": "errors", "text": "errors", "type": "number" },
      { "selector": "starts", "text": "sessions", "type": "number" },
      { "selector": "p50_load_time", "text": "p50", "type": "number" },
      { "selector": "error_rate", "text": "error_rate", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "$append(\n  $map(aggregations.web_apps.by_application.buckets, function($b) {\n    {\n      \"application\": $b.key,\n      \"starts\": $b.starts.doc_count,\n      \"errors\": $b.errors.doc_count,\n      \"error_rate\": $b.error_rate.value,\n      \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n    }\n  }),\n  $map(aggregations.mobile_apps.by_application.buckets, function($b) {\n    {\n      \"application\": $b.key,\n      \"starts\": $b.starts.doc_count,\n      \"errors\": $b.errors.doc_count,\n      \"error_rate\": $b.error_rate.value,\n      \"p50_load_time\": $b.p50_load_time.percentile.values.\"50.0\"\n    }\n  })\n)",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"size\": 0,\n  \"query\": {\n    \"bool\": {\n      \"filter\": [\n        {\n          \"range\": {\n            \"@timestamp\": {\n              \"gte\": \"${__from}\",\n              \"lte\": \"${__to}\"\n            }\n          }\n        },\n        { \"terms\": { \"session.media.id\": ${urns:json} }},\n        { \"wildcard\": { \"session.player.platform\": \"${platform}\" } },\n        { \"terms\": { \"event_name\": [\"ERROR\", \"START\"] } }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"web_apps\": {\n      \"filter\": {\n        \"bool\": {\n          \"must_not\": [\n            { \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] } }\n          ]\n        }\n      },\n      \"aggs\": {\n        \"by_application\": {\n          \"terms\": {\n            \"field\": \"session.media.short_origin\",\n            \"size\": 500\n          },\n          \"aggs\": {\n            \"errors\": {\n              \"filter\": {\n                \"bool\": {\n                  \"filter\": [\n                    { \"term\": { \"event_name\": \"ERROR\" } },\n                    { \"term\": { \"data.business_error\": false } }\n                  ],\n                  \"must_not\": [\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n                  ]\n                }\n              }\n            },\n            \"starts\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } }\n            },\n            \"error_rate\": {\n              \"bucket_script\": {\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n              }\n            },\n            \"p50_load_time\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\n              \"aggs\": {\n                \"percentile\": {\n                  \"percentiles\": {\n                    \"field\": \"session.qoe_timings.total\",\n                    \"percents\": [50]\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    },\n\n    \"mobile_apps\": {\n      \"filter\": {\n        \"terms\": { \"session.player.platform\": [\"Android\", \"android\", \"Apple\"] }\n      },\n      \"aggs\": {\n        \"by_application\": {\n          \"terms\": {\n            \"field\": \"session.application.id\",\n            \"size\": 500\n          },\n          \"aggs\": {\n            \"errors\": {\n              \"filter\": {\n                \"bool\": {\n                  \"filter\": [\n                    { \"term\": { \"event_name\": \"ERROR\" } },\n                    { \"term\": { \"data.business_error\": false } }\n                  ],\n                  \"must_not\": [\n                    { \"terms\": { \"data.error_type\": [\"DRM_NOT_SUPPORTED\", \"CONNECTION_ERROR\"] } }\n                  ]\n                }\n              }\n            },\n            \"starts\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } }\n            },\n            \"error_rate\": {\n              \"bucket_script\": {\n                \"buckets_path\": { \"err\": \"errors>_count\", \"sess\": \"starts>_count\" },\n                \"script\": \"params.sess > 0 ? params.err / params.sess : 0\"\n              }\n            },\n            \"p50_load_time\": {\n              \"filter\": { \"term\": { \"event_name\": \"START\" } },\n              \"aggs\": {\n                \"percentile\": {\n                  \"percentiles\": {\n                    \"field\": \"session.qoe_timings.total\",\n                    \"percents\": [50]\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_name:ERROR\nAND session.player.platform:${platform}\nAND session.media.id:${urns}\nAND data.business_error:false",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay",
   "type": "timeseries",
   "description": "The median quality of experience loading time, i.e., how long the user perceives the video to load.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session.qoe_timings.total", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" },
      { "id": "3", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${urns}\nAND session.player.platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Perceived delay historgram",
   "type": "barchart",
   "description": "Distribution of sessions across perceived loading times, capped at the 95th percentile to exclude outliers.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "session.qoe_timings.total", "id": "2", "settings": { "interval": "10", "min_doc_count": "10" }, "type": "histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND session.media.id:${urns}\nAND session.player.platform:${platform}\nAND session.qoe_timings.total:[* TO $p95]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Metrics", "type": "row" }
 ]
}